# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
platform :ios, '9.0'

target 'PayAsUGym' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PayAsUGym


  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'PayAsUGymTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PayAsUGym-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PayAsUGym-tvOS

  target 'PayAsUGym-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
